"""rejection count

Revision ID: 06f1e208f7d2
Revises: c35e77b686dc
Create Date: 2025-07-04 17:59:10.682351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f1e208f7d2'
down_revision: Union[str, None] = 'c35e77b686dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('game_rejection_count', sa.Integer(), nullable=True))
    op.drop_column('sessions', 'opted_out')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('opted_out', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'game_rejection_count')
    # ### end Alembic commands ###
