"""Added genre, tone and keywords

Revision ID: 112302e72f44
Revises: b1500424ee36
Create Date: 2025-07-23 19:09:18.030613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112302e72f44'
down_revision: Union[str, None] = 'b1500424ee36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_recommendations', sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('game_recommendations', sa.Column('tone', sa.String(), nullable=True))
    op.add_column('game_recommendations', sa.Column('keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_recommendations', 'keywords')
    op.drop_column('game_recommendations', 'tone')
    op.drop_column('game_recommendations', 'genre')
    # ### end Alembic commands ###
