"""Game, user, mood, plateform 

Revision ID: 273e2c1e2bfe
Revises: ae00ac022433
Create Date: 2025-06-20 11:47:00.279315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '273e2c1e2bfe'
down_revision: Union[str, None] = 'ae00ac022433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_cluster',
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('game_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('mood')
    )
    op.create_index(op.f('ix_mood_cluster_mood'), 'mood_cluster', ['mood'], unique=False)
    op.create_table('game_platforms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('game_vibes', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('game_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('games', sa.Column('mood_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.drop_column('games', 'platform')
    op.drop_column('games', 'embedding')
    op.add_column('users', sa.Column('platform_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('game_vibe', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'game_vibe')
    op.drop_column('users', 'platform_preference')
    op.add_column('games', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('games', 'mood_embedding')
    op.drop_column('games', 'game_embedding')
    op.drop_column('games', 'game_vibes')
    op.drop_table('game_platforms')
    op.drop_index(op.f('ix_mood_cluster_mood'), table_name='mood_cluster')
    op.drop_table('mood_cluster')
    # ### end Alembic commands ###
