"""update game

Revision ID: 4fb17612919f
Revises: fbae056c1f4d
Create Date: 2025-07-18 21:28:46.487902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '4fb17612919f'
down_revision: Union[str, None] = 'fbae056c1f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mechanic', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('graphical_visual_style', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('mood_tag', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('gameplay_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('games', sa.Column('preference_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('games', sa.Column('alternative_titles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('release_date', sa.String(), nullable=True))
    op.add_column('games', sa.Column('editions', sa.String(), nullable=True))
    op.add_column('games', sa.Column('subgenres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('story_setting_realism', sa.JSON(), nullable=True))
    op.add_column('games', sa.Column('main_perspective', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('gameplay_elements', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('advancement', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('linearity', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('themes', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('replay_value', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('developers', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('publishers', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('discord_id', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('igdb_id', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('sku', sa.String(), nullable=True))
    op.drop_column('games', 'mood_embedding')
    op.drop_column('games', 'mood_tags')
    op.drop_column('games', 'visual_style')
    op.drop_column('games', 'game_embedding')
    op.drop_column('games', 'mechanics')
    op.add_column('sessions', sa.Column('gameplay_elements', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('preferred_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('disliked_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('accepted_gameplay_styles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('rejected_gameplay_styles', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'rejected_gameplay_styles')
    op.drop_column('sessions', 'accepted_gameplay_styles')
    op.drop_column('sessions', 'disliked_keywords')
    op.drop_column('sessions', 'preferred_keywords')
    op.drop_column('sessions', 'gameplay_elements')
    op.add_column('games', sa.Column('mechanics', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('game_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('visual_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('mood_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('mood_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True))
    op.drop_column('games', 'sku')
    op.drop_column('games', 'igdb_id')
    op.drop_column('games', 'discord_id')
    op.drop_column('games', 'publishers')
    op.drop_column('games', 'developers')
    op.drop_column('games', 'replay_value')
    op.drop_column('games', 'themes')
    op.drop_column('games', 'linearity')
    op.drop_column('games', 'advancement')
    op.drop_column('games', 'gameplay_elements')
    op.drop_column('games', 'keywords')
    op.drop_column('games', 'main_perspective')
    op.drop_column('games', 'story_setting_realism')
    op.drop_column('games', 'subgenres')
    op.drop_column('games', 'editions')
    op.drop_column('games', 'release_date')
    op.drop_column('games', 'alternative_titles')
    op.drop_column('games', 'preference_embedding')
    op.drop_column('games', 'gameplay_embedding')
    op.drop_column('games', 'mood_tag')
    op.drop_column('games', 'graphical_visual_style')
    op.drop_column('games', 'mechanic')
    # ### end Alembic commands ###
