"""Add gameplay elements and keyword fields to Session model

Revision ID: 62616b8583b2
Revises: fbae056c1f4d
Create Date: 2025-07-18 11:23:55.501299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62616b8583b2'
down_revision: Union[str, None] = 'fbae056c1f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('gameplay_elements', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('preferred_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('disliked_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('accepted_gameplay_styles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('rejected_gameplay_styles', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'rejected_gameplay_styles')
    op.drop_column('sessions', 'accepted_gameplay_styles')
    op.drop_column('sessions', 'disliked_keywords')
    op.drop_column('sessions', 'preferred_keywords')
    op.drop_column('sessions', 'gameplay_elements')
    # ### end Alembic commands ###
