"""add field awaiting_reply

Revision ID: 7a3306b51eff
Revises: 43e9a68d18f7
Create Date: 2025-08-05 15:20:39.074223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a3306b51eff'
down_revision: Union[str, None] = '43e9a68d18f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'awaiting_reply')
    op.drop_column('sessions', 'last_thrum_timestamp')
    op.add_column('user_profiles', sa.Column('awaiting_reply', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_thrum_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'last_thrum_timestamp')
    op.drop_column('user_profiles', 'awaiting_reply')
    op.add_column('sessions', sa.Column('last_thrum_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('awaiting_reply', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
