"""update game platform

Revision ID: 7a95a71bfa6c
Revises: 4fb17612919f
Create Date: 2025-07-19 10:49:08.572382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a95a71bfa6c'
down_revision: Union[str, None] = '4fb17612919f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_platforms', sa.Column('distribution', sa.String(), nullable=True))
    op.add_column('games', sa.Column('key_features', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'key_features')
    op.drop_column('game_platforms', 'distribution')
    # ### end Alembic commands ###
