"""Added classification

Revision ID: 858127f15a10
Revises: 7a95a71bfa6c
Create Date: 2025-07-21 11:17:03.120767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '858127f15a10'
down_revision: Union[str, None] = '7a95a71bfa6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('complexity', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('games', 'mechanic')
    op.add_column('interactions', sa.Column('classification', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'classification')
    op.add_column('games', sa.Column('mechanic', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('games', 'complexity')
    # ### end Alembic commands ###
