"""Phase 1

Revision ID: 8e0d15d79547
Revises: 4396a33aeb9a
Create Date: 2025-07-02 15:29:27.933569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0d15d79547'
down_revision: Union[str, None] = '4396a33aeb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('intent_override_triggered', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('opted_out', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('shared_with_friend', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('tone_shift_detected', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('engagement_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'engagement_level')
    op.drop_column('sessions', 'tone_shift_detected')
    op.drop_column('sessions', 'shared_with_friend')
    op.drop_column('sessions', 'opted_out')
    op.drop_column('sessions', 'intent_override_triggered')
    # ### end Alembic commands ###
