"""Link

Revision ID: 920f5ecd6b8c
Revises: 92cbc778a71e
Create Date: 2025-07-11 19:16:13.040616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920f5ecd6b8c'
down_revision: Union[str, None] = '92cbc778a71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_platforms', sa.Column('link', sa.String(), nullable=True))
    op.drop_constraint(op.f('game_recommendations_user_id_fkey'), 'game_recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'game_recommendations', 'user_profiles', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('interactions_session_id_fkey'), 'interactions', type_='foreignkey')
    op.create_foreign_key(None, 'interactions', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'user_profiles', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'user_profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_session_id_fkey'), 'interactions', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'game_recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('game_recommendations_user_id_fkey'), 'game_recommendations', 'user_profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('game_platforms', 'link')
    # ### end Alembic commands ###
