"""Add memory

Revision ID: 92cbc778a71e
Revises: abc0a0b36dbf
Create Date: 2025-07-08 21:16:07.703027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92cbc778a71e'
down_revision: Union[str, None] = 'abc0a0b36dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('game_recommendations_user_id_fkey'), 'game_recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'game_recommendations', 'user_profiles', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('interactions_session_id_fkey'), 'interactions', type_='foreignkey')
    op.create_foreign_key(None, 'interactions', 'sessions', ['session_id'], ['session_id'])
    op.add_column('sessions', sa.Column('memory', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'user_profiles', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'user_profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('sessions', 'memory')
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_session_id_fkey'), 'interactions', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'game_recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('game_recommendations_user_id_fkey'), 'game_recommendations', 'user_profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
