"""Add phase 1

Revision ID: a9e6bf909ec6
Revises: 8e0d15d79547
Create Date: 2025-07-02 18:42:12.596035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e6bf909ec6'
down_revision: Union[str, None] = '8e0d15d79547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sessions', sa.Column('story_preference', sa.Boolean(), nullable=True))
    op.drop_column('sessions', 'mood_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('mood_tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'story_preference')
    op.drop_column('sessions', 'genre')
    # ### end Alembic commands ###
