"""Initial full schema

Revision ID: ae00ac022433
Revises: 
Create Date: 2025-06-13 14:39:50.816993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae00ac022433'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('response_type', sa.Enum('GameRec', 'Callback', 'ReEntry', 'IdleChat', name='responsetypeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'response_type')
    # ### end Alembic commands ###
