"""add fav game

Revision ID: b1500424ee36
Revises: 858127f15a10
Create Date: 2025-07-21 18:57:35.880935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1500424ee36'
down_revision: Union[str, None] = '858127f15a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('favourite_games', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('user_profiles', sa.Column('favourite_games', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'favourite_games')
    op.drop_column('sessions', 'favourite_games')
    # ### end Alembic commands ###
