"""Follow up keyword

Revision ID: c35e77b686dc
Revises: a9e6bf909ec6
Create Date: 2025-07-03 18:23:53.575254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35e77b686dc'
down_revision: Union[str, None] = 'a9e6bf909ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('followup_triggered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'followup_triggered')
    # ### end Alembic commands ###
