"""Added game vibe

Revision ID: fbae056c1f4d
Revises: 920f5ecd6b8c
Create Date: 2025-07-16 14:10:19.604825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbae056c1f4d'
down_revision: Union[str, None] = '920f5ecd6b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('game_recommendations_user_id_fkey'), 'game_recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'game_recommendations', 'user_profiles', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('interactions_session_id_fkey'), 'interactions', type_='foreignkey')
    op.create_foreign_key(None, 'interactions', 'sessions', ['session_id'], ['session_id'])
    op.add_column('mood_cluster', sa.Column('game_vibe', sa.ARRAY(sa.String()), nullable=True))
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'user_profiles', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'user_profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('mood_cluster', 'game_vibe')
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_session_id_fkey'), 'interactions', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'game_recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('game_recommendations_user_id_fkey'), 'game_recommendations', 'user_profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
